[project]
name = "cataract-detection-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ai-edge-litert>=2.1.2",
    "fastapi>=0.135.1",
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "gunicorn>=23.0.0",
    "numpy>=2.4.2",
    "pillow>=12.0.0",
    "python-multipart>=0.0.22",
    "tensorflow>=2.21.0",
    "uvicorn>=0.41.0",
]
